In [1]:
import numpy as np

In [3]:
a1D = np.array([1,2,3,4])
a2D = np.array([[1,2],[3,4]])
a3D = np.array([[[1,2], [3,4],[5,6], [7,8]]])

In [4]:
array1 = np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)

array2 = np.array([[1,2,3], [2,3,4,]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)


In [7]:
a = np.array([2,3,5,7])
b = np.array([[4,5,6,7],[8,9,10,11]])
c = np.array([[[4,5,6,7],[8,9,10,11], [12,13,14,15]]])
print(a)
print(b)
print(c)

[2 3 5 7]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


In [16]:
#1번
'''np.diag([1,1,1,1])'''
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
#2번
np.arange(0, 21, 3 )

array([ 0,  3,  6,  9, 12, 15, 18])

In [22]:
#3번
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.diag(array1)

In [21]:
#4번np.indices((3,5))

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [24]:
#1번 
array1=np.array([0,1,2,3,4])
b = array1.copy()
b*=2
print(array1, b)

[0 1 2 3 4] [0 2 4 6 8]


In [26]:
#2번
array2 = np.array([10,20,30,40])
b = np.array([50,60,70,80])
np.vstack((array2,b))

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [27]:
#3번
array2 = np.array([10,20,30,40])
b = np.array([50,60,70,80])
np.hstack((array2,b))

array([10, 20, 30, 40, 50, 60, 70, 80])

In [31]:
array2 = np.array([10,20,30,40])
b = np.array([50,60,70,80])
np.block([array2, b])
np.block([[array2],[b]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [37]:
#1번
array1= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array1.shape

(3, 4)

In [34]:
#2번
array2 = np.array([[101,102,103,104], [105,106,107,108]])
array2.shape
#곱할 수 없다. 왜냐하면 어느한쪽의 행과 다른한쪽의 열이 서로 다르기 때문이다.
#차원의 크기가 달라서 곱할 수 없다.

(2, 4)

In [38]:
#3번
array1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [45]:
#4번
array4 = np.arange(180)
array4.reshape(10,18)
array4.reshape(10,-1)
array4.reshape(-1,18)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
         31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
         49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
         67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161],
       [162, 163, 164, 165, 166, 167,

In [48]:
#슬라이싱 실습 1
array = np.arange(start=0, stop=40).reshape(5,8)
print(array[:, 3]) # : 쓰는 것에 유의해라

[ 3 11 19 27 35]


In [49]:
#2
print(array[1, 3:6])


[11 12 13]


In [52]:
#3
print(array[2:5, 5:8]) # ' : = ~ '로 이해하면 편하다

[[21 22 23]
 [29 30 31]
 [37 38 39]]


In [51]:
#4
print(array[1::2, ::3])

[[ 8 11 14]
 [24 27 30]]
